### ISSUE TITLE
Update site link is broken

### ISSUE THREAD

**Issue by sonnesen** [mnlipp/EclipseMinifyBuilder#2]
Hello,

I'm trying to install the plugin on my Eclipse IDE but the update site link is broken.
https://mnlipp.github.io/EclipseMinifyBuilder/update-site/

Att.
Winston

**Comment by mnlipp** [comment]
Seems like github changed the URLs to access raw content without any notice (or I used an unsupported pattern in the first place). Anyway, I've updated the URL. Please try again.

**Comment by sonnesen** [comment]
It's still not working. Bellow is the error log:

Unable to read repository at https://raw.githubusercontent.com/mnlipp/EclipseMinifyBuilder/gh-pages/update-site/content.xml.
Unable to read repository at https://raw.githubusercontent.com/mnlipp/EclipseMinifyBuilder/gh-pages/update-site/content.xml.
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

I'm using:
- Eclipse Java EE IDE for Web Developers.
Version: Photon Release (4.8.0)
Build id: 20180619-1200
- Linux Mint 19 64-bit
- openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

**Comment by mnlipp** [comment]
I'm sorry, but I cannot reproduce your problem. I've downloaded the "Eclipse IDE for Java EE Developers" (I suppose you meant this one), tried it, and I can install without any problem.

I wonder where you got that "content.xml" from in the repository URL. It's not in the published URLs. Did you add that yourself? If yes, it explains your problem. Update site URL are directory URLs (usually end with a slash explicitly).

**Comment by sonnesen** [comment]
Today I received an update of Linux Mint and after applying the update I was able to install the plugin. The update received was ca-certificates-java version 20180516ubuntu1~18.04.1.
