### ISSUE TITLE
Minify doesn't work on Eclipse 2018-09 build

### ISSUE THREAD

**Issue by godsgood33** [mnlipp/EclipseMinifyBuilder#4]
I've got the minifier installed on my new Eclipse 2018-09 build (20180917-1800) and it is not minifying CSS and JS.  I've verified that it is enabled and the YUI compressor is selected in the file properties...

![image](https://user-images.githubusercontent.com/1922710/48664113-e0de5b80-ea67-11e8-8bac-cf158fa1a104.png)

Suggestions?

**Comment by mnlipp** [comment]
It works for me (same Eclipse build id). Maybe your JS source has parts that cannot be handled by the YUI compressor (such es ECMAscript 6 statements). What happens if you feed your JS source to the YUI compressor using the [command line interface](http://yui.github.io/yuicompressor/#using)?

**Comment by godsgood33** [comment]
Hey, sorry it took so long to respond.  Running the command line works fine (v2.4.8).  I've also run it through this compressor https://www.piliapp.com/minify/yui-compressor/ and it works fine here too.  Just a pain to have to do the extra step of manually doing the compressing...I got spoiled by your plugin.

Also of note, I upgraded to the 2018-12 Eclipse build.  I'm willing to email or post one of the files that is not working.  I'm not getting an errors in the Eclipse editor itself so I don't think there are any syntax problems and it works in the other compressors.

**Comment by mnlipp** [comment]
Just to be perfectly clear about this: it works for some files in your project and does not for others, right? Or does the plugin work in one of your projects and does not work in another project? In the latter case, you may have forgotten to enable the minify builder for the project (on project right click | Configure).

If you have enabled the builder for the project *and* building for the files in question, I'd really need one of the  not-working file to investigate this further.

**Comment by godsgood33** [comment]
I have not be able to get it to work in any of the projects or any of the files that I've tried for the Eclipse build.

Attached is an example file that doesn't work.  I ran it through the online compressor and it worked.  I have verified that the minifier is enabled at the project and file levels. (had to add .txt to the end for it to post in the issue, so just download and remove the extension then try compressing it)

[index.js.txt](https://github.com/mnlipp/EclipseMinifyBuilder/files/2712969/index.js.txt)

**Comment by mnlipp** [comment]
Mmh, sorry. But I cannot reproduce the problem. I've created a new Java project, added a directory "resources", put your file into that directory, enabled the Minify builder for the project and the building for the file and `index.min.js` was created (here's the [exported project](https://github.com/mnlipp/EclipseMinifyBuilder/files/2713019/MinifyTest.zip)).

Can you check if there's anything in your Eclipse log file?

**Comment by godsgood33** [comment]
These are the last few entries in the log.

!ENTRY org.eclipse.egit.ui 2 0 2018-12-27 10:48:59.200
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\godsg'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

**!ENTRY org.eclipse.equinox.p2.repository 2 0 2018-12-27 10:49:57.075
!MESSAGE Server returned lastModified <= 0 for https://raw.githubusercontent.com/mnlipp/EclipseMinifyBuilder/gh-pages/update-site/content.jar**

!ENTRY org.eclipse.equinox.p2.metadata.repository 2 0 2018-12-27 10:49:57.528
!MESSAGE Error parsing metadata repository
!SUBENTRY 1 org.eclipse.equinox.p2.core 2 0 2018-12-27 10:49:57.528
!MESSAGE Error in file:/C:/Users/godsg/.p2/org.eclipse.equinox.p2.repository/cache/content566841349.jar at line 592, column 62: Missing required attribute in "property": value
!SUBENTRY 1 org.eclipse.equinox.p2.core 2 0 2018-12-27 10:49:57.528
!MESSAGE Error in file:/C:/Users/godsg/.p2/org.eclipse.equinox.p2.repository/cache/content566841349.jar at line 1401, column 62: Missing required attribute in "property": value
!SUBENTRY 1 org.eclipse.equinox.p2.core 2 0 2018-12-27 10:49:57.528
!MESSAGE Error in file:/C:/Users/godsg/.p2/org.eclipse.equinox.p2.repository/cache/content566841349.jar at line 1646, column 62: Missing required attribute in "property": value
!SUBENTRY 1 org.eclipse.equinox.p2.core 2 0 2018-12-27 10:49:57.528
!MESSAGE Error in file:/C:/Users/godsg/.p2/org.eclipse.equinox.p2.repository/cache/content566841349.jar at line 2387, column 62: Missing required attribute in "property": value
!SUBENTRY 1 org.eclipse.equinox.p2.core 2 0 2018-12-27 10:49:57.528
!MESSAGE Error in file:/C:/Users/godsg/.p2/org.eclipse.equinox.p2.repository/cache/content566841349.jar at line 2706, column 62: Missing required attribute in "property": value
!SUBENTRY 1 org.eclipse.equinox.p2.core 2 0 2018-12-27 10:49:57.528
!MESSAGE Error in file:/C:/Users/godsg/.p2/org.eclipse.equinox.p2.repository/cache/content566841349.jar at line 3073, column 62: Missing required attribute in "property": value

!ENTRY org.eclipse.jface 2 0 2018-12-27 11:02:08.487
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2018-12-27 11:02:08.487
!MESSAGE A conflict occurred for CTRL+SHIFT+N:
Binding(CTRL+SHIFT+N,
	ParameterizedCommand(Command(org.pdtextensions.core.ui.command.phpcsfixer,Run PHP-CS-Fixer,
		Run PHP-CS-Fixer on files and folders,
		Category(org.eclipse.core.commands.categories.autogenerated,Uncategorized,Commands that were either auto-generated or have no category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@905e189,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.php.core.phpsource,,,system)
Binding(CTRL+SHIFT+N,
	ParameterizedCommand(Command(org.eclipse.php.debug.ui.commands.InspectDelegate,Inspect,
		Inspect result of evaluating selected text,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7b31281b,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.php.ui.phpEditorScope,,,system)

**Comment by mnlipp** [comment]
The highlighted message, that has "MinifyBuilder" in it, appears in my log file as well. I assume that it originates from Eclipse trying to check for updates (and the github server not being so nice as to provide a Last-Modified header). Obviously, it does not prevent the proper operation.

In general, I consider it a bit strange that you have errors in cached content files. I have no such errors in my log, so maybe you should empty the cache. But this is, of course, not directly related to the MinifyBuilder.

Apart from that I'm afraid that I have run out of ideas now.

**Comment by godsgood33** [comment]
I deleted all the files in that cache directory that it mentions.  Any other locations I should clear?

**Comment by mnlipp** [comment]
You should [start eclipse with the -clean option](https://stackoverflow.com/questions/2030064/how-to-run-eclipse-in-clean-mode-and-what-happens-if-we-do-so).

**Comment by godsgood33** [comment]
Okay, looks like I figured it out.  I removed Eclipse and deleted all meta data from my workspace.  After reloading it appears to work.
