### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by jotakar** [mnlipp/EclipseMinifyBuilder#5]
Is there any user guide  about this plugin? I cannot see how to enable and execute it.
I've installed, ok.
Then I can configure project for use Minify. 
But now I see the only way to minify is doing it for each file, I mean: i select a file then config it, select the minify option and then aply and close.... is there a way to do it for a set of files or for all the inlided files in project?

Thanks

**Comment by mnlipp** [comment]
There is no user guide, setting the behavior for individual files is all there is. This is appropriate for my projects which are mainly Java/Python server side projects and only contain a few files that are "run" in the browser.

IMHO you should use the minify features of your build system if you plan anything that needs project wide settings.

**Comment by jotakar** [comment]
Thanks for your answer.
Indeed is not easy to find a minify/merger tool, at least one easy to use.  
At last I used a php script to read all js files in a single file and then I minified it with your minify plugin, and it works fine :).

**Comment by Ronef** [comment]
Hi,

I don't understand how can i execute it. I've configured Minifier at the file properties page, then clicked to `Apply and close` button, but nothing happens ¯\\_(ツ)\_/¯ What else should I do?

Thanks

**Comment by jotakar** [comment]
Sorry, I left this app long time ago.

**Comment by mnlipp** [comment]
> I don't understand how can i execute it. I've configured Minifier at the file properties page, then clicked to `Apply and close` button, but nothing happens ¯\_(ツ)_/¯ What else should I do?

Did you "Enable the builder for your project in Project/Configure" as mentioned in the project's README?

**Comment by Ronef** [comment]
@mnlipp Yes, i do.

Today i understand that i must click `Build Project` and it worked! 🎉 

I sent you PR #9 

Many thanks for your work! 🖤

**Comment by mnlipp** [comment]
> Today i understand that i must click `Build Project` and it worked! tada

Have you disabled automatic build?

**Comment by Ronef** [comment]
> Have you disabled automatic build?

I don't remember doing that 🙂 But yes, it's disabled.

Anyway, i think README description must be improved.
