### ISSUE TITLE
Minified file with only one line

### ISSUE THREAD

**Issue by manoletto** [mnlipp/EclipseMinifyBuilder#6]
Hello,

don't know if this is configured by your plugin or not,
but is there an option to make minified file on only one line.

i mean get :
.......................;

instead :
......;
......;
......;

Thky

**Comment by mnlipp** [comment]
No there is not, at least not in the EclipseMinifyBuilder-GUI. There may be such an option in the minifier programs used by EclipseMinifyBuilder, but the idea of EclipseMinifyBuilder is to provide an easy to use ad hoc tool for simple situations.

**Comment by manoletto** [comment]
ok, thank you 😉

___________________________
Emmanuel Fournier
06 16 79 20 50
mailto:emmanuel.fournier@free.fr
mailto:emmanuelfournier8@gmail.com
