### ISSUE TITLE
Plugin doesn't work?

### ISSUE THREAD

**Issue by F3rrY** [mnlipp/EclipseMinifyBuilder#8]
Hello.

I wasted 2h this morning trying to configure the plugin in Eclipse and I can't do anything, the files .min don't change.

I tell you the test that I did:
     1.- I installed the plugin from marketplace
     2.- Import plugin.xml (I put the file from github repository) to the project
     3.- Right click on "Project" => Properties => Builders => new "Ant Builder"
     4,.- In Main tab => Buildfile => I selected the plugin.xml file and then "Apply Changes".
     5.- So, on a .css or .js file, right click => Properties => Minify CSS and I select YUI Compressor

So, I edit the .css file and when I save it, the file .min.css don't change. And finally, in the git staging only see the changes of .css, but not the .min.css

Bonus track: If I go to "Run" and I select "Build", Eclipse fails with this error: plugin.xml:3: Unexpected element "{}plugin" {antlib:org.apache.tools.ant}plugin

What's wrong?

Thanks.

**Comment by mnlipp** [comment]
I lost you on step 2. Why would you want to "import plugin.xml"? And what has the "Ant builder" got to do with my plugin?

**Comment by F3rrY** [comment]
Hi mnlipp.

The step 2-3-4 is because I saw in the "Usage" of the readme.md: "**Enable the builder for your project in Project/Configure.**"

However, if only install the plugin from Marketplace and do the step 5, don't do nothing :(

**Comment by mnlipp** [comment]
Right-click on project | Configure | Enable Minify Builder

**Comment by F3rrY** [comment]
Bingo!

I did that you comment and then, in a .css file => Right-click => Properties and select Minify CSS => YUI Compressor.

So, when edit the .css file, the -min.css edits too automatically.

Thanks for your help mnlipp, good job :)

**Comment by mnlipp** [comment]
Thanks.
